export const groupType = {
  GET_GROUPS_DETAIL: "GET_GROUPS_DETAIL",
  GET_SUB_GROUPS_DETAIL: "GET_SUB_GROUPS_DETAIL",
  GET_GROUP_DETAIL: "GET_GROUP_DETAIL",
  GET_ONLY_GROUPS: "GET_ONLY_GROUPS",
  REMOVE_GROUP: "REMOVE_GROUP",
};
